#!/bin/bash
set -e

mkdir -p /srv/www/${BASE_DIR}/logs /srv/www/${BASE_DIR}/www

cd /etc/apache2/sites-available
envsubst < vhost.tpl > vhost.conf

rm -f /usr/local/apache2/logs/httpd.pid
exec apache2 -DFOREGROUND
